<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFwdQj83\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFwdQj83/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerFwdQj83.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerFwdQj83\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerFwdQj83\App_KernelDevContainer([
    'container.build_hash' => 'FwdQj83',
    'container.build_id' => 'baeb0b3e',
    'container.build_time' => 1677236709,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFwdQj83');
